ShoppingList.WebMVC/Areas/UserPanel/Models/HomeVM/ListViewModel.cs
namespace ShoppingList.WebMVC.Areas.UserPanel.Models.HomeVM
{
    public class ListViewModel
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Name { get; set; }
        public bool status { get; set; }
        public int ProductCount { get; set; }
        
    }
}

ShoppingList.WebMVC/Areas/UserPanel/Controllers/ListsController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ShoppingList.Domain.Entities;
using ShoppingList.WebMVC.Areas.AdminPanel.Models.CategoryVM;
using ShoppingList.WebMVC.Areas.AdminPanel.Models.ProductVM;
using ShoppingList.WebMVC.Areas.UserPanel.Models.HomeVM;
using ShoppingList.WebMVC.Areas.UserPanel.Models.ListsVM;
using ShoppingList.WebMVC.Models;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Security.Policy;
using System.Text;
using static System.Net.WebRequestMethods;

namespace ShoppingList.WebMVC.Areas.UserPanel.Controllers
{
    [Area("UserPanel")]
    public class ListsController : Controller
    {
        string responsejwt = "";
        private void AddJwtTokenToRequest(HttpClient httpClient, string token)
        {
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
        }

        private bool SessionCheck()
        {
            responsejwt = HttpContext.Session.GetString("SessionUser");
            if (string.IsNullOrEmpty(responsejwt))
            {
                return false;
            }
            var handler = new JwtSecurityTokenHandler();
            var token = handler.ReadJwtToken(responsejwt);
            var roleClaim = token.Claims.FirstOrDefault(claim => claim.Type == ClaimTypes.Role);
            if (roleClaim == null || roleClaim.Value != "User")
            {

                return false;

            }
            return true;

        }
        
        public async Task<IActionResult> Index(string name = null,string listid=null, string listname=null)
        {

            MyListViewModel model = new MyListViewModel();
            var httpClient2 = new HttpClient();

            AddJwtTokenToRequest(httpClient2, responsejwt);

            var responseMessage2 = await httpClient2.GetAsync("https://localhost:44344/api/productlists/ProductListDetail/" + listid);
            if (responseMessage2.StatusCode == System.Net.HttpStatusCode.NotFound)
            {
                TempData["ProductListMessage"] = "Listeye henüz bir ürün eklemediniz!";
                model.ProductListsVM = null;

            }
            else {
            var jsonString2 = await responseMessage2.Content.ReadAsStringAsync();
            List<ProductListsVM> values2 = JsonConvert.DeserializeObject<List<ProductListsVM>>(jsonString2);
                

                model.ProductListsVM = values2;
                
            }

            var httpClient = new HttpClient();

            AddJwtTokenToRequest(httpClient, responsejwt);

            var responseMessage = await httpClient.GetAsync("https://localhost:44344/api/Products");

            if (responseMessage.StatusCode == System.Net.HttpStatusCode.NotFound)
            {

                return RedirectToAction("Index", "Home");

            }
            var jsonString = await responseMessage.Content.ReadAsStringAsync();
            List<ProductDetailDTOVM> values = JsonConvert.DeserializeObject<List<ProductDetailDTOVM>>(jsonString);

            
            
            model.ProductDetailDTOVM = values;


            if (name != null)
            {
                var resultData = values.Where(x => x.Name.ToLower().Contains(name.ToLower()));
                ViewBag.Name = name;
                ViewBag.ListName = listname;
                ViewBag.ListId = listid;
                model.ProductDetailDTOVM = resultData.ToList();
                return View(model);
                
            }

            ViewBag.ListName = listname;
            ViewBag.ListId = listid;

            return View(model);
           
            
        }

        [HttpPost]
        public async Task<ActionResult> Add(int id, int listid, string listname) 
        {
            string name = "";
            ProductListsVM list = new ProductListsVM();
            list.ProductId = id;
            list.ListId = listid;
            list.Description = "";
            list.Status = true;

            string url = "https://localhost:44344/api/ProductLists";

            string controlurl = "https://localhost:44344/api/ProductLists?listid=" + listid;

            HttpClient client = new HttpClient();

            var responseMessage = await client.GetAsync(controlurl);

            if (responseMessage.StatusCode == System.Net.HttpStatusCode.OK)
            {
                var jsonString2 = await responseMessage.Content.ReadAsStringAsync();
                List<ProductListsVM> values2 = JsonConvert.DeserializeObject<List<ProductListsVM>>(jsonString2);
                var productlist = values2.FirstOrDefault(x => x.ProductId == id);
                if (productlist is not null)
                {
                    TempData["ProductAddError"] = "Bu ürün listenizde zaten ekli.";
                    return RedirectToAction("Index", new { name, listid, listname });
                }
            }

            var jsonList = JsonConvert.SerializeObject(list);
            var content = new StringContent(jsonList, Encoding.UTF8, "application/json");
            var response = await client.PostAsync(url, content);

            
            if (response.StatusCode == System.Net.HttpStatusCode.Created)
            {
               
                return RedirectToAction("Index", new { name, listid, listname });
            }
            else if (response.StatusCode == System.Net.HttpStatusCode.NotFound)
            {
                string errorMessage = await response.Content.ReadAsStringAsync();
                TempData["Message"] = errorMessage;
                return RedirectToAction("Index", new { name, listid, listname });
            }
            else if (response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
            {
                string errorMessage = await response.Content.ReadAsStringAsync();
                TempData["Message"] = errorMessage;
                return RedirectToAction("Index", new { name, listid, listname });
            }

            return RedirectToAction("Index", new { name, listid, listname });

        }




        [HttpPost]
        public async Task<IActionResult> Delete(int id, string listname, string listid)
        {

            if (!SessionCheck())
            {
                return RedirectToAction("Index", "Login", new { area = "" });
            }
            string name = "";
            string url = "https://localhost:44344/api/ProductLists/" + id;
            HttpClient client = new HttpClient();

            var response = await client.DeleteAsync(url);
            if (response.StatusCode == System.Net.HttpStatusCode.NoContent)
            {
                return RedirectToAction("Index", new { name, listid, listname });

            }
            else if (response.StatusCode == System.Net.HttpStatusCode.NotFound)
            {
                string errorMessage = await response.Content.ReadAsStringAsync();
                TempData["Error"] = errorMessage;
                return RedirectToAction("Index", new { name, listid, listname });
            }
            return RedirectToAction("Index", new { name, listid, listname });
        }


        [HttpPost]
        public async Task<IActionResult> Update(UpdateProductListVM updateProductListVM)
        {
            if (!SessionCheck())
            {
                return RedirectToAction("Index", "Login", new { area = "" });
            }

            string name = "";
            
            
                
                string url = "https://localhost:44344/api/ProductLists/" + updateProductListVM.id;
                
               
                

                HttpClient client = new HttpClient();
                var jsonCategory = JsonConvert.SerializeObject(updateProductListVM);
                var content = new StringContent(jsonCategory, Encoding.UTF8, "application/json");
                var response = await client.PutAsync(url, content);
            if (response.IsSuccessStatusCode)
            {

                return RedirectToAction("Index", new { name, updateProductListVM.listid, updateProductListVM.listname });

            }
            else if (response.StatusCode == HttpStatusCode.BadRequest)
            {
                var jsonString = await response.Content.ReadAsStringAsync();
                var validation = JsonConvert.DeserializeObject<ErrorResponse>(jsonString);
                foreach (var key in validation.errors.Keys)
                {
                    foreach (var error in validation.errors[key])
                    {
                        ModelState.AddModelError(key, error);
                        TempData["ModelError"]=error;
                    }

                }

                return RedirectToAction("Index", new { name, updateProductListVM.listid, updateProductListVM.listname });
            }
            return RedirectToAction("Index", new { name, updateProductListVM.listid, updateProductListVM.listname });
          
        }

        [HttpPost]
        public async Task<IActionResult> ShoppingGo(int listid, string listname)
        {
            if (!SessionCheck())
            {
                return RedirectToAction("Index", "Login", new { area = "" });
            }
            string name = null;
            string url = "https://localhost:44344/api/Lists/" + listid;

            var handler = new JwtSecurityTokenHandler();
            var token = handler.ReadJwtToken(responsejwt);
            var roleSid = token.Claims.FirstOrDefault(claim => claim.Type == ClaimTypes.Sid);
                    
            UpdateListVM updateListVM = new UpdateListVM();
            updateListVM.Userid =Convert.ToInt32(roleSid.Value);
            updateListVM.Name = listname;
            updateListVM.Status = false;
           

                

ShoppingList.WebMVC/Areas/UserPanel/Views/Lists/Delete.cshtml
@using ShoppingList.WebMVC.Areas.UserPanel.Models.ListsVM;

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}
@model ProductListsVM
<h1>Delete</h1>

<!-- Modal Liste Silme -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Ürünü listeden kaldırmak üzeresiniz! -@Model.ListId - @Model.ListName - @Model.id
            </div>
            <div class="modal-body">
                 <form id="deleteForm" action="/User/lists/delete" method="post">
                <div class="mb-3">
                <input name="listid" type="text" value="@Model.ListId" hidden class="form-control">
                </div>
                <div class="mb-3">
                <label class="form-label">Liste Adı</label>
                        <input name="listname" type="text" class="form-control" value="@Model.ListName" hidden >
                </div>
                <button type="submit" class="btn btn-danger">Ürünü Sil</button>
                </form>

                <form id="iptalForm" asp-action="index" asp-controller="lists" asp-area="userpanel" asp-route-listid="@Model.ListId" asp-route-listname="@Model.ListName" method="post">
                    <button type="submit" class="btn btn-secondary">İptal</button>
                </form>
                @* <button asp-action="index" asp-route-name="" asp-route-listid="@Model.ListId" asp-route-listname="@Model.ListName" type="button" class="btn btn-secondary">İptal</button> *@
                @* </form> *@
            </div>

        </div>
    </div>
</div>




@* <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script> *@

@section scripts {
    <script>
        $(document).ready(function () {
            // Sayfa yüklendiğinde modal'ı göster
            $('#staticBackdrop').modal('show');
        });

    </script>
}

ShoppingList.WebMVC/Areas/UserPanel/Views/Lists/Index.cshtml
@using ShoppingList.WebMVC.Areas.AdminPanel.Models.ProductVM;
@using ShoppingList.WebMVC.Areas.UserPanel.Models.ListsVM;

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}
@model MyListViewModel








<div class="container">
    <div class="shadow-lg p-3 mb-5 bg-body-tertiary rounded my-4"><h2 class="text-center text-primary">@ViewBag.ListName </h2></div>


    <div class="row">

        <div class="col-4">
            <div class="card shadow-lg p-3 mb-5 bg-body-tertiary rounded">
                <div class="card-header">
                    <h3>  Listene Ürün Ekle</h3>
                    <div class="card-body">
                        <form method="get" id="filter">
                            <div class="form-group">
                                <input id="productName" name="name" class="form-control" placeholder="Ürün Ara" value="@ViewBag.Name" />
                                <input name="listid" value="@ViewBag.ListId" hidden />
                                <input name="listname" value="@ViewBag.ListName" hidden />
                            </div>
                            <div class="form-group mt-2"><button class="btn btn-primary">Filtrele</button></div>

                        </form>
                        <table class="table table-striped my-2">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>

                                    <th scope="col">Görsel</th>
                                    <th scope="col">Ürün</th>
                                    <th scope="col">Kategori</th>

                                    <th scope="col">İşlem</th>

                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var product in Model.ProductDetailDTOVM)
                                {
                                    <form method="post" asp-action="Add">
                                    <tr>
                                        <th scope="row">@product.Id</th>

                                        <td scope="row"><img src="@product.UrlImage" width="25"></td>
                                        <td>@product.Name</td>
                                        <td>@product.CategoryName</td>
                                        <td>

                                            <button class="btn btn-primary" asp-controller="Lists" asp-area="UserPanel" asp-action="Add" asp-route-id="@product.Id" asp-route-listid="@ViewBag.ListId" asp-route-listname="@ViewBag.ListName">Ekle</button>
                                        </td>

                                    </tr>
                                    </form>
                                }


                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-8">
            <div class="card shadow-lg p-3 mb-5 bg-body-tertiary rounded">
                <div class="card-header">
                    <h3> Alış Veriş Listeniz </h3>
                    <div class="card-body">
                        @{
                            if (Model.ProductListsVM is not null)
                            {
                                <form method="post" asp-controller="Lists" asp-action="shoppinggo" asp-route-listid="@ViewBag.ListId" asp-route-listname="@ViewBag.ListName">
                                <button class="btn btn-success" type="submit" >Alışverişe Çık</button>
                                </form>
                            }
                        }

                        <table class="table table-striped my-2">
                            <thead>
                                <tr>


                                   @*  <th scope="col">ProductId</th> *@
                                    <th scope="col">Görsel</th>
                                    <th scope="col">Ürün</th>
                                   @*  <th scope="col">Kategori</th> *@
                                    <th scope="col">Açıklama</th>
                                   @*  <th scope="col">status</th> *@
                                    <th scope="col">Güncelle</th>
                                    <th scope="col">Sil</th>
                                </tr>
                            </thead>
                            <tbody>

                                @{
                                    if (TempData["ProductAddError"] is not null)
                                    {

                                        <div class="alert alert-danger" role="alert">
                                            @TempData["ProductAddError"]
                                        </div>
                                    }
                                    if (TempData["ModelError"] is not null)
                                    {

                                        <div class="alert alert-danger" role="alert">
                                            @TempData["ModelError"]
                                        </div>
                                    }
                                    
                                    if (TempData["ProductListMessage"] is not null)
                                    {

                                        <div class="alert alert-danger" role="alert">
                                            @TempData["ProductListMessage"]
                                        </div>
                                    }
                                    else
                                    {

                                        @foreach (var productlist in Model.ProductListsVM)
                                        {
                                            string duzenle = ""; duzenle = "duzenle" + productlist.id;

                                            @* burası düzenleme yapılırken modal olarak popup penceresi açacak. *@
                                            <div class="modal fade" id="@duzenle" tabindex="-1" role="dialog" aria-hidden="true">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title">Açıklama Ekle-@productlist.id - @productlist.ListId - @productlist.ListName</h5>
                                                            <button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
                                                        </div>
                                                        <div class="modal-body">
                                                            <form asp-action="Update"  method="post">
                                                                <div class="mb-3">
                                                                    <input class="form-control" type="text" required="" hidden="" readonly="" name="id" value="@productlist.id">
                                                                    <input class="form-control" type="text" required="" hidden="" readonly="" name="listname" value="@productlist.ListName">
                                                                    <input class="form-control" type="text" required="" hidden="" readonly="" name="status" value="true">
                                                                    <input class="form-control" type="text" required="" hidden="" readonly="" name="listid" value="@productlist.ListId">
                                                                    <img src="@productlist.ProductImageUrl" width="25">
                                                                    <label class="col-form-label" for="recipient-name">@productlist.ProductName</label>
                                                                </div>
                                                                
                                                                <div class="mb-3">
                                                                    <label class="col-form-label" for="recipient-name">Açıklama Girin (Adet/Kg/Litre vs.)</label>
                                                                    <input class="form-control" type="text" name="Description" value="@productlist.Description">
                                                                </div>
                                                               
                                                                <div class="modal-footer">
                                                                    <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Vazgeç</button>
                                                                    <button class="btn btn-warning" type="submit">Güncelle</button>
                                                                </div>
                                                            </form>
                                                        </div>

                                                    </div>
                                                </div>
                                            </div>




                                            <form method="post" asp-action="Add">
                                            <tr>
                                                    @* <th scope="row">@productlist.id</th>*@
                                                <td scope="row"><img src="@productlist.ProductImageUrl" width="25"></td>
                                                <th scope="row">@productlist.ProductName</th>
                                                @* <td>@productlist.ListId</td>*@
                                                    @* <td scope="row"><img src="@productlist.UrlImage" width="25"></td> *@
                                                <td>@productlist.Description</td>
                                                @* <td>@productlist.Status</td>*@
                                                <td>
                                                    <a class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#@duzenle"><i class="icon-pencil"></i> Açıklama Ekle</a>
                                                    </td>
                                                    <td>

                                                    <button class="btn btn-danger" asp-controller="Lists" asp-action="delete" asp-route-id="@productlist.id" asp-route-listid="@ViewBag.ListId" asp-route-listname="@ViewBag.ListName">Sil</button>

                                                        @{
                                                            TempData[productlist.id.ToString()] = @productlist.ListName;
                                                        }
                                                    
                                                </td>

                                            </tr>
                                            </form>
                                        }

                                    }
                                }




                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

ShoppingList.WebMVC/Areas/UserPanel/Views/Lists/ListView.cshtml
@using ShoppingList.WebMVC.Areas.UserPanel.Models.ListsVM;

@{
    ViewData["Title"] = "ListView";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}
@model List<ListViewVM>
<h1>ListView</h1>

<div class="col-8">
    <div class="card shadow-lg p-3 mb-5 bg-body-tertiary rounded">
        <div class="card-header">
            <h3> Alış Veriş Listeniz </h3>
            <div class="card-body">
                @{
                    if (Model.Count>0)
                    {
                        <form method="post" asp-controller="Lists" asp-action="ShoppingFinish" asp-route-listid="@ViewBag.ListId" asp-route-listname="@ViewBag.ListName">
                            <button class="btn btn-success" type="submit">Alışverişi Bitir</button>
                        </form>
                    }
                }

                <table class="table table-striped my-2">
                    <thead>
                        <tr>


                            <th scope="col">ProductId</th>
                            <th scope="col">Görsel</th>
                            <th scope="col">ProductName</th>
                            <th scope="col">ListId</th>
                            <th scope="col">Description</th>
                            <th scope="col">status</th>
                            <th scope="col">İşlem</th>

                        </tr>
                    </thead>
                    <tbody>

                        @{
                            if (TempData["ProductAddError"] is not null)
                            {

                                <div class="alert alert-danger" role="alert">
                                    @TempData["ProductAddError"]
                                </div>
                            }
                            if (TempData["ModelError"] is not null)
                            {

                                <div class="alert alert-danger" role="alert">
                                    @TempData["ModelError"]
                                </div>
                            }

                            if (TempData["ProductListMessage"] is not null)
                            {

                                <div class="alert alert-danger" role="alert">
                                    @TempData["ProductListMessage"]
                                </div>
                            }
                            else
                            {

                                @foreach (var productlist in Model.Where(item=>item.Status==true))
                                {
                                   
                                    <form method="post" asp-action="Add">
                                    <tr>
                                        <th scope="row">@productlist.Id</th>
                                        <td scope="row"><img src="@productlist.ProductImageUrl" width="25"></td>
                                        <th scope="row">@productlist.ProductName</th>
                                        <td>@productlist.ListId</td>
                                           
                                        <td>@productlist.Description</td>
                                        <td>@productlist.Status</td>
                                        <td>
                                            


                                            <button class="btn btn-danger" asp-controller="Lists" asp-action="updatelist" asp-route-id="@productlist.Id" asp-route-listid="@ViewBag.ListId" asp-route-listname="@ViewBag.ListName">Aldım</button>

                                                

                                        </td>

                                    </tr>
                                    </form>
                                }

                            }
                        }




                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>